/// Flutter icons DemosIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DemosIcons
///      fonts:
///       - asset: fonts/DemosIcons.ttf
///
/// 
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class DemosIcons {
  DemosIcons._();

  static const _kFontFam = 'DemosIcons';
  static const String? _kFontPkg = null;

  static const IconData close_circle = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_outlined = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_proposal = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back_arrow = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back_circle = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData big_close = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData building = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_outlined = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checked = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData config = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dislike = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData done_circle = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData done = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData empty_proposals = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData empty_space_outlined = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exit = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_outlined = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_outlined = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData members = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_outlined = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notes_outlined = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notes = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData proposal = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData role = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slider = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData space = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timer = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_card = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vote = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_member = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData empty_spaces = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_space = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
